"""Added Rainamount

Revision ID: 608248177d92
Revises: 62d28a7d6ec4
Create Date: 2024-05-19 08:10:49.820552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608248177d92'
down_revision: Union[str, None] = '62d28a7d6ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wheater_data', sa.Column('rain_amount', sa.Double(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wheater_data', 'rain_amount')
    # ### end Alembic commands ###
