"""Initial Migration Raspy

Revision ID: 62d28a7d6ec4
Revises: 
Create Date: 2024-05-18 22:12:46.232777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d28a7d6ec4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wheater_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Double(), nullable=True),
    sa.Column('humidity', sa.Double(), nullable=True),
    sa.Column('wind_speed', sa.Double(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wheater_data')
    op.drop_table('location')
    # ### end Alembic commands ###
